- construction_api.go
- construction_impl.go
- construction_impl_test.go
closes #9;
Waiting for more information...
> unsigned transaction represented as base64 string

- .circleci/config.yml
- construction_api.go
- construction_impl.go
- construction_impl_test.go
> add basic linter + fixes

- construction_api.go
- construction_impl.go
- construction_impl_test.go
> Update ParseTX to take base64 string as argument and returned value

- .circleci/config.yml
- construction_api.go
- construction_impl.go
- construction_impl_test.go
- Adds more extensive linters #14 
- Standardize on uint64 #13 
- ParseTx now uses strings #12 
- Use base64 for strings #15
> API improvements + refactoring

- .gitignore
- construction_impl.go
- construction_impl_test.go
For the 3 on chain tests verify the `ExitCode` returned. Make sure it is 0.
> Verify ExitCode for on chain test

- construction_impl_test.go
Fix the multisig swap test logic.
> Fix test logic for multisig swap

- construction_api.go
- construction_impl.go
- construction_impl_test.go
- construction_onchain_test.go
- construction_parsing_test.go
- go.mod
- go.sum
> Add support for multisig param decoding

- construction_api.go
- construction_impl.go
- construction_impl_test.go
- construction_onchain_test.go
- go.sum
> Support quantities as strings

- construction_impl_test.go
- construction_onchain_test.go
Fix tests to use devnet's actors. Closes #51
> Devnet tests

- construction_api.go
- construction_impl.go
- construction_impl_test.go
Fix using "Swap on "Remove".
Should fix #54
> Fix using wrong methods call

- construction_impl_test.go
- construction_onchain_test.go
Just to be sure it is parse in the right order.
> Test gas field order

- construction_impl.go
This PR fixes parsing the parameters of a multisig `propose` tx for V3 actors.
> Fix parse V3 multisig params

- construction_impl.go
> added v4 multisig constructor

- go.mod
- go.sum
> Support for lotus v1.8.0

- construction_impl.go
- construction_impl_test.go
- construction_onchain_test.go
This PR add support for V5 multisig actor.
The V5 multisig actors doesn't have any changes from V4 (see https://github.com/filecoin-project/specs-actors/pull/1399/files#diff-e456e5b9630c6260c31f2952d9d0eafb2c24a18657e3c3ec8e820ddfba98e59e).
> Update to V5 actors

- construction_impl.go
- Add "Send" case in `getMinerMethodString`
- Move function `getMsigMethodString` near `getMinerMethodString` and `getVerifRegMethodString`
> Add "Send" case for miners

- go.mod
- go.sum
:link: [zboto Link](https://app.clickup.com/t/2n9vr1z)
> Bump lotus release

- go.mod
- go.sum
:link: [zboto Link](https://app.clickup.com/t/2n9wznu)
> Bump filecoin-actors-cids

- actors/actors.go
- actors/legacy.go
- construction_impl.go
- go.mod
- Add legacy support in functions: `GetActorNameFromCid`,  `IsActor`, `ParseParamsMultisigTx` and `GetProposedMethod`
:link: [zboto Link](https://app.clickup.com/t/2v6p5f3)
> Add support for getting legacy actors codes and names

- .sonarcloud.properties
- construction_impl.go
- construction_impl_test.go
:link: [zboto Link](https://app.clickup.com/t/8677h4uv7)
> Fix: support for f410 addresses 

- construction_impl.go
- construction_impl_test.go
:link: [zboto Link](https://app.clickup.com/t/8677hzhye)
> feat: add conversion from eth to fil addr

- go.mod
- go.sum
:link: [zboto Link](https://app.clickup.com/t/8677w9ftm)
> Bump lotus

- v10.go
:link: [zboto Link](https://app.clickup.com/t/861myhxqu)
> add: exported methods

- go.mod
- go.sum
:link: [zboto Link](https://app.clickup.com/t/869339d22)
> Bump to lotus v1.24.0-rc5

- go.mod
- go.sum
ClickUp: [https://app.clickup.com/t/8693rcdyd](https://app.clickup.com/t/8693rcdyd)
> Upgrade lotus v1.26.0-rc3

- go.mod
- go.sum
:link: [zboto Link](https://app.clickup.com/t/86952q64u)
> Bump lotus to v1.28.0-rc5

- go.mod
- go.sum
:link: [zboto Link](https://app.clickup.com/t/869ah76fn)
> Support lotus v1.34.1
